set(pa_version_major 2)
set(pa_version_minor 2)
set(pa_version_patch 7)
set(pa_version ${pa_version_major}.${pa_version_minor})

set(PACKAGE_VERSION ${pa_version})
if(PACKAGE_FIND_VERSION_MAJOR)
    if("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "${pa_version_major}")
        if ("${PACKAGE_FIND_VERSION_MINOR}" EQUAL "${pa_version_minor}")
            set(PACKAGE_VERSION_EXACT TRUE)
        elseif("${PACKAGE_FIND_VERSION_MINOR}" LESS "${pa_version_minor}")
            set(PACKAGE_VERSION_COMPATIBLE TRUE)
        else()
            set(PACKAGE_VERSION_UNSUITABLE TRUE)
        endif()
    else()
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
    endif()
endif()
